#!/usr/bin/env python
# -*- coding: utf-8 -*-


import os, sys


_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, _filepath)



import you_get
if __name__ == '__main__':
    you_get.main(repo_path=_filepath)
